Hw02 express
YuriiSenenko/nodejs-homework-rest-api pull request #1
Opened 2023-01-23 18:23 UTC by YuriiSenenko

2023-01-23 19:44 UTC, Eastvarga requested changes
Є зауваження, особливо працюйте над логікою, а заголом не погано.

2023-01-23 19:44 UTC, Eastvarga commented on middlewares/validationMiddleware.js
> +        message: "missing required name field",
Тут повинна бути помилка валідації повертатись у відповіді

2023-01-23 19:44 UTC, Eastvarga commented on middlewares/validationMiddleware.js
> +      return res.status(400).json({ message: "missing fields" });
теж саме

2023-01-23 19:44 UTC, Eastvarga commented on middlewares/validationMiddleware.js
> +    });
Добре, а якщо це буде патч метод та використовувати будете опціональні поля? Поки подумайте про це

2023-01-23 19:44 UTC, Eastvarga commented on models/contacts.js
> +  if (searchContact === undefined) {
не потрібно if (!searchContact) достатньо - приведення типів треба знати

2023-01-23 19:44 UTC, Eastvarga commented on models/contacts.js
> +    return;
Повертати можна саму змінну а чи вона пуста вже перевіряти

2023-01-23 19:44 UTC, Eastvarga commented on models/contacts.js
> +    return Error;
Зовсім невірно! можете повернути екземпляр класу но не сам клас. А клас помилки зовсім не повертається, зазвичай помилка кидається

2023-01-23 19:44 UTC, Eastvarga commented on routes/api/contacts.js
> +  if (delelteContact === Error) {
Для чого тут Error? судячи з логіки можна просто повертати або ніщо або невизначеність та зробити
if (!delelteContact) - приведення типів до буля вчіться використвувати, та не вигадувати щой неймовірне.

2023-01-23 20:34 UTC, YuriiSenenko commented on models/contacts.js
> +    return;
Цей if просто забув видалити

2023-01-23 20:42 UTC, YuriiSenenko commented on middlewares/validationMiddleware.js
> +    });
Тоді не потрібно буде вказувати .required()

2023-01-23 21:02 UTC, YuriiSenenko commented on middlewares/validationMiddleware.js
> +        message: "missing required name field",
Я правильно зрозумів, що користувачу повинно повертатись значення помилки? Уточніть будь ласка.

2023-01-24 07:39 UTC, Eastvarga commented on middlewares/validationMiddleware.js
> +        message: "missing required name field",
Так, валідація генерує помилки відносно Вашої схеми, отже Вам залишається повернути їх як відповідь, коли вони є.

2023-01-24 07:42 UTC, Eastvarga commented on middlewares/validationMiddleware.js
> +    });
а якщо у тілі запиту не буде жодного поля з опціональних, як зробити щоб схема згенерувала помилку відсутності полів (пусте тіло запиту)?

2023-01-24 07:45 UTC, Eastvarga approved these changes

2023-01-24 07:45 UTC, merged

2023-01-24 08:10 UTC, YuriiSenenko commented on middlewares/validationMiddleware.js
> +        message: "missing required name field",
> Так, валідація генерує помилки відносно Вашої схеми, отже Вам залишається повернути їх як відповідь, коли вони є.

Я вас зрозумів, і це логічно. Збиває з толку те що в ТЗ було вказано конкретне повідомлення помилки, яке повинно повертатись, а код повинен відповідати ТЗ