Hw03 mongodb
YuriiSenenko/nodejs-homework-rest-api pull request #2
Opened 2023-01-28 08:03 UTC by YuriiSenenko

2023-01-28 15:36 UTC, Eastvarga requested changes
Є декілька зауважень

2023-01-28 15:36 UTC, Eastvarga commented on controllers/postController.js
> +  res.status(201).json({ newContact });
res.status(201).json( newContact ); достатньо, дужки зайві

2023-01-28 15:36 UTC, Eastvarga commented on controllers/postController.js
> +  res.json({ updatedContact });
теж саме

2023-01-28 15:36 UTC, Eastvarga commented on db/connection.js
> +    const mongoDB = await mongoose.connect(process.env.MONGOOSE_URL);
краще усі змінні проекту винести до окремого файлу конфігурацій, та імпортувати звідти туди де вони потрібні

2023-01-28 17:44 UTC, YuriiSenenko commented on db/connection.js
> +    const mongoDB = await mongoose.connect(process.env.MONGOOSE_URL);
я змінну mongoDB взагалі видалив, вона не потрібна

2023-01-28 17:48 UTC, YuriiSenenko commented on db/connection.js
> +    const mongoDB = await mongoose.connect(process.env.MONGOOSE_URL);
І виніс в окремий файл звернення до БД, правда не знаю чи є зараз в цьому якийсь смисл

2023-01-29 10:15 UTC, Eastvarga commented on db/connection.js
> +    const mongoDB = await mongoose.connect(process.env.MONGOOSE_URL);
Погане розуміння потрібності змінних.
Якщо треба ключ для використання  сторонніх сервісів, він потрібен бути у зміних середовища, а отже його Ви імпортуєте всеодно зі зміної процесу попередньо її ініціалізувавши. Я бачу логіки, повернувшись до проекту через місяць - шукати де я його використовую по коду, тому заходжу у файл конфігкрацій та змінюю що мені потрібно або переходжу туди, де я його використав.

2023-01-29 10:21 UTC, Eastvarga requested changes
Не використовуйте безліке іменування, це дуже погано

2023-01-29 10:21 UTC, Eastvarga commented on config.js
> +  return await Contact.findByIdAndUpdate(contactId, {
await зайвий всеодно повертаєте проміс, отже можна
const update = async (contactId, data) => {
  return Contact.findByIdAndUpdate(...) використовувати, однак і так праацюватиме

2023-01-29 12:28 UTC, YuriiSenenko commented on db/connection.js
> +    const mongoDB = await mongoose.connect(process.env.MONGOOSE_URL);
Я переніс значення strictQuery в змінну середовища. Справді не розумію, що саме вимагається від мене в цьому файлі. Дякую за терпіння!

2023-01-29 17:45 UTC, Eastvarga approved these changes
Прийнято

2023-01-29 17:45 UTC, Eastvarga commented on db/connection.js
>      await mongoose.connect(process.env.MONGOOSE_URL);
process.env.MONGOOSE_URL - це змінна сервера отже
Щось таке я мав на увазі
const DB_HOST = process.env.MONGOOSE_URL;
.....

const {DB_HOST} =  require("./configuration.js");
await mongoose.connect(DB_HOST);

2023-01-29 17:45 UTC, merged