Hw06 email
YuriiSenenko/nodejs-homework-rest-api pull request #6
Opened 2023-02-20 12:36 UTC by YuriiSenenko

2023-02-20 18:47 UTC, Eastvarga requested changes
Є зауваження.

2023-02-20 18:47 UTC, Eastvarga commented on controllers/authController.js
>    );
avatarURL = \`http://localhost:${PORT}/avatars/${id}_${originalname}`
ось вірне рішення.

2023-02-20 18:47 UTC, Eastvarga commented on helpers/emailValidation.js
> +    html: `Please, confirm your email adress, POST http://localhost:3000/users/verify/${verificationToken}`,
тут потрібен бути html контент не просто строка - наприклад tag \< a> зі шляхом \`http://localhost:3000/users/verify/${verificationToken}`

2023-02-20 18:47 UTC, Eastvarga commented on servises/authService.js
> +  }
Ось це робить мідлвар валідації. Вам потрібно зробити схему валідації, створити мідлвар валідації тіла запиту, встановити його попереду контроллера у рауті де reVerification  використовується.
З попередніх завдань Ви повинні були засвоїти алгоритм створення раутів.

2023-02-20 18:47 UTC, Eastvarga commented on servises/authService.js
> +    await fs.rename(tmpUpload, avatarURL);
Ось це зовсім невірно, avatarURL нічого спільного з файловою системою не має, Ви не можете використовувати його, попередній варіант буд доречніше

2023-02-21 09:03 UTC, YuriiSenenko commented on servises/authService.js
> +  }
Згоден, в мене була в роуті підключена валідація email із "bodyValidationForUpdate", тільки там не вказано що поле обов'язкове. і так як в завданні було конкретно написано: Якщо в body немає обов'язкового поля email, повертає json з ключем {"message":"missing required field email"} і статусом 400. А потім написано: ResponseBody: <Помилка від Joi або іншої бібліотеки валідації> Тому я вирішив перевикористати валідацію правильності email, а валідацію body написати окремо щоб вона видавала саме ту відповідь яку вимагали в завданні.

2023-02-21 19:12 UTC, Eastvarga approved these changes

2023-02-21 19:12 UTC, merged